#pragma once

#include "./tensor/aligned.hpp"
#include "./tensor/base.hpp"
#include "./tensor/block.hpp"
#include "./tensor/cat.hpp"
#include "./tensor/constants.hpp"
#include "./tensor/ewise_ops.hpp"
#include "./tensor/extend.hpp"
#include "./tensor/index.hpp"
#include "./tensor/map.hpp"
#include "./tensor/permute.hpp"
#include "./tensor/remap.hpp"
#include "./tensor/reformulate.hpp"
#include "./tensor/shape.hpp"
#include "./tensor/tensor.hpp"
